
spring:
  datasource:
    url: jdbc:postgresql://localhost:6543/database
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true

